### ISSUE TITLE
Hello, is there a sample picture that can be run？

### ISSUE THREAD

**Issue by ZealZW** [lyangas/depthmap_from_jpeg#1]
Hello, is there a sample picture that can be run？

**Comment by lyangas** [comment]
> Hello, is there a sample picture that can be run？

Hello, yes - I added the image to the repository and made some minor fixes in the code.

p.s.
for this program you need images taken in "portrait" mode on your Iphone

**Comment by ZealZW** [comment]
I get it，thank you very much
